name: qibla
description: "Aplikasi Arah Kiblat."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  flutter_qiblah: ^3.1.0+1
  http: ^1.6.0
  geolocator: ^13.0.4
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Coolvetica
      fonts:
        - asset: assets/fonts/Coolvetica Rg.otf
